<?xml version="1.0"?>
<doc>
    <assembly>
        <name>DynaBIMToolbox</name>
    </assembly>
    <members>
        <member name="M:Solids.SolidsAPI.GetWallSolid(Revit.Elements.Wall)">
            <summary>
            Get the Autodesk.DB.Solid for the specified wall
            </summary>
            <param name="hostModelWall"> Wall instance </param>
            <returns> Autodesk.DB.Solid || The solid, representing the wall Geometry in the API </returns>
            <search> wall, solid, API </search>
        </member>
        <member name="M:Solids.SolidsAPI.GetWallSolidTransformed(Revit.Elements.Wall,Autodesk.Revit.DB.RevitLinkInstance)">
            <summary>
            Get the Autodesk.DB.Solid for the specified wall from linked model
            </summary>
            <param name="linkModelWall"> Wall || A wall instance from linked model </param>
            <param name="linkInstance"> Wall || A wall instance from linked model </param>
            <returns> Autodesk.DB.Solid || The solid, representing the wall Geometry in the API </returns>
            <search> wall, solid, API </search>
        </member>
        <member name="M:Solids.SolidsAPI.ReturnDynamoSolid(Autodesk.Revit.DB.Solid)">
            <summary>
            Wrap Revit Autodesk.Revit.DB.Solid to get Dynamo solid
            </summary>
            <param name="solid"> Solid || Autodesk.Revit.DB.Solid </param>
            <returns> Autodesk.DesignScript.Geometry || Dynamo Solid </returns>
            <search> solid, API, Dynamo </search>
        </member>
        <member name="M:Solids.SolidsAPI.RevitAPIExtrusionFromCurve(Autodesk.DesignScript.Geometry.Curve,System.Double,System.Double)">
            <summary>
            Create Autodesk.Revit.DB.Solid from a single curve, by offseting the curve in both direction, creating closed curveloop and extruding it
            </summary>
            <param name="line"> [points] || A straight Dynamo line </param>
            <param name="width"> height || A specified width for the offset </param>
            <param name="height"> Height for the extrusion </param>
            <returns> Autodesk.Revit.DB.Solid || Revit API solid </returns>
            <search> solid, API, Dynamo </search>
        </member>
        <member name="M:Solids.SolidsAPI.RevitAPIExtrusionFromCurveTransformed(Autodesk.DesignScript.Geometry.Curve,System.Double,System.Double,Autodesk.Revit.DB.RevitLinkInstance)">
            <summary>
            Create Autodesk.Revit.DB.Solid from a single curve, by offseting the curve in both direction, creating closed curveloop, extruding and transforming its coordinate system
            </summary>
            <param name="line"> [points] || A straight Dynamo line </param>
            <param name="width"> height || A specified width for the offset </param>
            <param name="height"> Height for the extrusion </param>
            <param name="linkInstance"> Height for the extrusion </param>
            <returns> Autodesk.Revit.DB.Solid || Revit API solid </returns>
            <search> solid, API, Dynamo </search>
        </member>
        <member name="M:Solids.SolidsAPI.TranslateSolidVertically(Autodesk.Revit.DB.Solid,System.Double)">
            <summary>
            Translate Autodesk.revit.DB.Solid along the Z axis at the specified distance
            </summary>
            <param name="solid"> [points] || A straight Dynamo line </param>
            <param name="translation"> height || A specified width for the offset </param>
            <returns> Autodesk.Revit.DB.Solid || Revit API solid </returns>
            <search> solid, API, Dynamo, translate, vertical </search>
        </member>
    </members>
</doc>
